apiVersion: v1
kind: Service
metadata:
  name: item-api
  namespace: default
  labels:
    app: item-api
spec:
  type: LoadBalancer
  ports:
  - name: service
    port: 8082
  selector:
    app: item-api
---
apiVersion: v1
kind: Service
metadata:
  name: discount-api
  namespace: default
  labels:
    app: discount-api
spec:
  type: LoadBalancer
  ports:
  - name: service
    port: 8081
  selector:
    app: discount-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-api
  namespace: default
  labels:
    app: item-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: item-api
  template:
    metadata:
      labels:
        app: item-api
    spec:
      containers:
      - name: item-api
        image: image-prefix/item-api:v1.0.0
        ports:
        - name: service
          containerPort: 8082
      nodeSelector:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-api
  namespace: default
  labels:
    app: discount-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-api
  template:
    metadata:
      labels:
        app: discount-api
    spec:
      containers:
      - name: discount-api
        image: image-prefix/discount-api:v1.0.0
        ports:
        - name: service
          containerPort: 8081
      nodeSelector:
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: item-api
  namespace: default
spec:
  routes:
  - name: 'GET /item/{id}'
    condition:
      all:
      - method: GET
      - pathRegex: /item/(.*)
    responseClasses:
    - condition:
        status:
          min: 500
          max: 599
      isFailure: true
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: discount-api
  namespace: default
spec:
  routes:
  - name: 'GET /discount/{time}/{id}'
    condition:
      all:
      - method: GET
      - pathRegex: /discount/\d+/(.*)
    responseClasses:
    - condition:
        status:
          min: 500
          max: 599
      isFailure: true
